export const ROUTES = {
  LOGIN: "/login",
  INVESTOR_DASHBOARD: "/investor/dashboard",
  INVESTOR_INVESTMENTS: "/investor/investments",
  INVESTOR_MESSAGES: "/investor/messages",
  INVESTOR_KYC: "/investor/kyc",
  INVESTOR_SECURITY: "/investor/security",
  INVESTOR_MILESTONES: "/investor/milestones",
  INVESTOR_PROJECTS: "/investor/projects",
  INVESTOR_MEMBERSHIP: "/investor/membership",
  OWNER_DASHBOARD: "/owner/dashboard",
  OWNER_PROJECTS: "/owner/projects",
  OWNER_MESSAGES: "/owner/messages",
  OWNER_OFFERS: "/owner/offers",
  OWNER_MILESTONES: "/owner/milestones",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_USERS: "/admin/users",
  ADMIN_PROJECTS: "/admin/projects",
  ADMIN_PAYMENTS: "/admin/payments",
  ADMIN_SECURITY: "/admin/security",
  ADMIN_COMPLAINTS: "/admin/complaints",
} as const;
